language: go

go:
    - master # This uses automatically the latest version of go

branches:
  only:
    - gh-pages

install:
    - go get github.com/spf13/hugo # This provides the latest version of Hugo to Travis CI

script:
    - hugo # This commands builds your website on travis
    - echo 'www.mengtanx.com' > public/CNAME

deploy:
    local_dir: public # Default static site output dir for Hugo
    repo: mengtanx/mengtanx.com # This is the slug of the repo you want to deploy your site to
    target_branch: master # GitHub pages branch to deploy to (in other cases it can be gh-pages)
    provider: pages
    skip_cleanup: true
    github_token: ${GITHUB_TOKEN} # This is the authentication which you will setup in the next step in travis-ci dashboard
    email: mengtanx@gmail.com
    name: ${GITHUB_USERNAME}
    on:
    branch: gh-pages